{{- range $key, $value := .Values.workers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.secretName }}
  namespace: kube-system
data:
  script: {{ include "shoot-cloud-config.execution-script" (set (set $.Values "worker" $value) "Capabilities" $.Capabilities) | b64enc }}
{{- end }}
